# Generated by Django 5.0.2 on 2024-02-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_subscribers_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('chapter_name', models.CharField(blank=True, null=True)),
                ('noof_units', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(blank=True, null=True)),
                ('unit_description', models.TextField(blank=True, null=True)),
                ('artical', models.TextField(blank=True, null=True)),
                ('chapter_belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.chapter')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
