# Generated by Django 5.0.2 on 2024-02-25 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0006_chapter_chapter_video_chapter_expire_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
